import pkg from './index.js';
export const {
    makeWASocket,
    proto,
    generateWAMessageFromContent,
    generateWAMessage,
    generateWAMessageContent,
    extractMessageContent,
    getContentType,
    normalizeMessageContent,
    downloadMediaMessage,
    downloadContentFromMessage,
    toBuffer,
    getDevice,
    prepareWAMessageMedia,
    jidDecode,
    jidEncode,
    jidNormalizedUser,
    areJidsSameUser,
    DisconnectReason,
    Browsers,
    patchSocket,
    makeFreeZeeSocket,
    makeInMemoryStore,
    smsg,
    fetchLatestBaileysVersion,
    delay,
    generateMessageID,
    S_WHATSAPP_NET,
    OFFICIAL_BIZ_JID,
    getAllStatusSenders,
    getStatusesFrom,
    getStatusCounts,
    onStatusUpdate,
    downloadStatusMedia,
    useMultiFileAuthState,
    useMongoFileAuthState,
    getMediaInfo
} = pkg;

export default makeWASocket;
