import pkg from './index.js';
export const {
    makeWASocket,
    makeInMemoryStore,
    proto,
    generateWAMessageFromContent,
    generateWAMessage,
    generateWAMessageContent,
    extractMessageContent,
    getContentType,
    normalizeMessageContent,
    jidNormalizedUser,
    jidDecode,
    jidEncode,
    areJidsSameUser,
    DisconnectReason,
    Browsers,
    delay,
    WA_DEFAULT_EPHEMERAL,
    MessageType,
    MessageOptions,
    MIMETYPE_MAP,
    downloadMediaMessage,
    downloadContentFromMessage,
    toBuffer,
    getDevice,
    prepareWAMessageMedia,
    patchSocket,
    useMongoFileAuthState,
    useMultiFileAuthState,
    makeFreeZeeSocket,
    smsg,
    fetchLatestBaileysVersion,
    getAllStatusSenders,
    getStatusesFrom,
    getStatusCounts,
    onStatusUpdate,
    downloadStatusMedia
} = pkg;

export default makeWASocket;
