/* ULTIMATE AUTO-GENERATED ESM INDEX */
import * as auth_utils from "./auth-utils.js";
export const addTransactionCapability = auth_utils.addTransactionCapability;
export const initAuthCreds = auth_utils.initAuthCreds;
import * as browser_utils from "./browser-utils.js";
export const Browsers = browser_utils.Browsers;
export const getPlatformId = browser_utils.getPlatformId;
import * as business from "./business.js";
export const parseCatalogNode = business.parseCatalogNode;
export const parseCollectionsNode = business.parseCollectionsNode;
export const parseOrderDetailsNode = business.parseOrderDetailsNode;
export const toProductNode = business.toProductNode;
export const parseProductNode = business.parseProductNode;
export const uploadingNecessaryImages = business.uploadingNecessaryImages;
import * as chat_utils from "./chat-utils.js";
export const newLTHashState = chat_utils.newLTHashState;
export const encodeSyncdPatch = chat_utils.encodeSyncdPatch;
export const decodeSyncdMutations = chat_utils.decodeSyncdMutations;
export const decodeSyncdPatch = chat_utils.decodeSyncdPatch;
export const extractSyncdPatches = chat_utils.extractSyncdPatches;
export const downloadExternalBlob = chat_utils.downloadExternalBlob;
export const downloadExternalPatch = chat_utils.downloadExternalPatch;
export const decodeSyncdSnapshot = chat_utils.decodeSyncdSnapshot;
export const decodePatches = chat_utils.decodePatches;
export const chatModificationToAppPatch = chat_utils.chatModificationToAppPatch;
export const processSyncAction = chat_utils.processSyncAction;
import * as crypto from "./crypto.js";
export const generateSignalPubKey = crypto.generateSignalPubKey;
export const Curve = crypto.Curve;
export const signedKeyPair = crypto.signedKeyPair;
import * as decode_wa_message from "./decode-wa-message.js";
export const getDecryptionJid = decode_wa_message.getDecryptionJid;
export const NO_MESSAGE_FOUND_ERROR_TEXT = decode_wa_message.NO_MESSAGE_FOUND_ERROR_TEXT;
export const MISSING_KEYS_ERROR_TEXT = decode_wa_message.MISSING_KEYS_ERROR_TEXT;
export const DECRYPTION_RETRY_CONFIG = decode_wa_message.DECRYPTION_RETRY_CONFIG;
export const NACK_REASONS = decode_wa_message.NACK_REASONS;
export const extractAddressingContext = decode_wa_message.extractAddressingContext;
export const decryptMessageNode = decode_wa_message.decryptMessageNode;
import * as event_buffer from "./event-buffer.js";
export const makeEventBuffer = event_buffer.makeEventBuffer;
import * as freezee_socket from "./freezee-socket.js";
export const makeFreeZeeSocket = freezee_socket.makeFreeZeeSocket;
import * as generics from "./generics.js";
export const baileysVersion = generics.baileysVersion;
export const BufferJSON = generics.BufferJSON;
export const initAuthCreds = generics.initAuthCreds;
export const generateMdTagPrefix = generics.generateMdTagPrefix;
export const delay = generics.delay;
export const toNumber = generics.toNumber;
export const unixTimestampSeconds = generics.unixTimestampSeconds;
export const unpadRandomMax16 = generics.unpadRandomMax16;
export const writeRandomPadMax16 = generics.writeRandomPadMax16;
export const encodeWAMessage = generics.encodeWAMessage;
export const encodeBigEndian = generics.encodeBigEndian;
export const generateRegistrationId = generics.generateRegistrationId;
export const generateMessageIDV2 = generics.generateMessageIDV2;
export const generateMessageID = generics.generateMessageID;
export const Browsers = generics.Browsers;
export const fetchLatestBaileysVersion = generics.fetchLatestBaileysVersion;
export const getKeyAuthor = generics.getKeyAuthor;
export const trimUndefined = generics.trimUndefined;
export const promiseTimeout = generics.promiseTimeout;
export const bindWaitForEvent = generics.bindWaitForEvent;
export const getCodeFromWSError = generics.getCodeFromWSError;
export const getErrorCodeFromStreamError = generics.getErrorCodeFromStreamError;
export const encodeNewsletterMessage = generics.encodeNewsletterMessage;
export const generateParticipantHashV2 = generics.generateParticipantHashV2;
import * as history from "./history.js";
export const downloadHistory = history.downloadHistory;
export const processHistoryMessage = history.processHistoryMessage;
export const downloadAndProcessHistorySyncNotification = history.downloadAndProcessHistorySyncNotification;
export const getHistoryMsg = history.getHistoryMsg;
import * as link_preview from "./link-preview.js";
export const getUrlInfo = link_preview.getUrlInfo;
import * as logger from "./logger.js";
import * as lt_hash from "./lt-hash.js";
export const LT_HASH_ANTI_TAMPERING = lt_hash.LT_HASH_ANTI_TAMPERING;
import * as make_mutex from "./make-mutex.js";
export const makeMutex = make_mutex.makeMutex;
export const makeKeyedMutex = make_mutex.makeKeyedMutex;
import * as message_retry_manager from "./message-retry-manager.js";
import * as messages_media from "./messages-media.js";
export const hkdfInfoKey = messages_media.hkdfInfoKey;
export const getRawMediaUploadData = messages_media.getRawMediaUploadData;
export const extractImageThumb = messages_media.extractImageThumb;
export const encodeBase64EncodedStringForUpload = messages_media.encodeBase64EncodedStringForUpload;
export const generateProfilePicture = messages_media.generateProfilePicture;
export const mediaMessageSHA256B64 = messages_media.mediaMessageSHA256B64;
export const toReadable = messages_media.toReadable;
export const toBuffer = messages_media.toBuffer;
export const getStream = messages_media.getStream;
export const getHttpStream = messages_media.getHttpStream;
export const encryptedStream = messages_media.encryptedStream;
export const getUrlFromDirectPath = messages_media.getUrlFromDirectPath;
export const downloadContentFromMessage = messages_media.downloadContentFromMessage;
export const downloadEncryptedContent = messages_media.downloadEncryptedContent;
export const getWAUploadToServer = messages_media.getWAUploadToServer;
export const encryptMediaRetryRequest = messages_media.encryptMediaRetryRequest;
export const decodeMediaRetryNode = messages_media.decodeMediaRetryNode;
export const decryptMediaRetryData = messages_media.decryptMediaRetryData;
export const getStatusCodeForMediaRetry = messages_media.getStatusCodeForMediaRetry;
import * as messages from "./messages.js";
export const extractUrlFromText = messages.extractUrlFromText;
export const generateLinkPreviewIfRequired = messages.generateLinkPreviewIfRequired;
export const prepareWAMessageMedia = messages.prepareWAMessageMedia;
export const prepareDisappearingMessageSettingContent = messages.prepareDisappearingMessageSettingContent;
export const generateForwardMessageContent = messages.generateForwardMessageContent;
export const generateWAMessageContent = messages.generateWAMessageContent;
export const generateWAMessageFromContent = messages.generateWAMessageFromContent;
export const generateWAMessage = messages.generateWAMessage;
export const getContentType = messages.getContentType;
export const normalizeMessageContent = messages.normalizeMessageContent;
export const extractMessageContent = messages.extractMessageContent;
export const getDevice = messages.getDevice;
export const updateMessageWithReceipt = messages.updateMessageWithReceipt;
export const updateMessageWithReaction = messages.updateMessageWithReaction;
export const updateMessageWithPollUpdate = messages.updateMessageWithPollUpdate;
export const updateMessageWithEventResponse = messages.updateMessageWithEventResponse;
export const aggregateMessageKeysNotFromMe = messages.aggregateMessageKeysNotFromMe;
export const downloadMediaMessage = messages.downloadMediaMessage;
export const assertMediaContent = messages.assertMediaContent;
import * as noise_handler from "./noise-handler.js";
export const makeNoiseHandler = noise_handler.makeNoiseHandler;
import * as pre_key_manager from "./pre-key-manager.js";
import * as process_message from "./process-message.js";
export const cleanMessage = process_message.cleanMessage;
export const isRealMessage = process_message.isRealMessage;
export const shouldIncrementChatUnread = process_message.shouldIncrementChatUnread;
export const getChatId = process_message.getChatId;
import * as signal from "./signal.js";
export const createSignalIdentity = signal.createSignalIdentity;
export const getPreKeys = signal.getPreKeys;
export const generateOrGetPreKeys = signal.generateOrGetPreKeys;
export const xmppSignedPreKey = signal.xmppSignedPreKey;
export const xmppPreKey = signal.xmppPreKey;
export const parseAndInjectE2ESessions = signal.parseAndInjectE2ESessions;
export const extractDeviceJids = signal.extractDeviceJids;
export const getNextPreKeys = signal.getNextPreKeys;
export const getNextPreKeysNode = signal.getNextPreKeysNode;
import * as socket_patcher from "./socket-patcher.js";
export const patchSocket = socket_patcher.patchSocket;
import * as use_mongo_file_auth_state from "./use-mongo-file-auth-state.js";
export const useMongoFileAuthState = use_mongo_file_auth_state.useMongoFileAuthState;
import * as use_multi_file_auth_state from "./use-multi-file-auth-state.js";
export const useMultiFileAuthState = use_multi_file_auth_state.useMultiFileAuthState;
import * as validate_connection from "./validate-connection.js";
export const generateLoginNode = validate_connection.generateLoginNode;
export const generateRegistrationNode = validate_connection.generateRegistrationNode;
export const configureSuccessfulPairing = validate_connection.configureSuccessfulPairing;
export const encodeSignedDeviceIdentity = validate_connection.encodeSignedDeviceIdentity;

export * from "./auth-utils.js";
export * from "./browser-utils.js";
export * from "./business.js";
export * from "./chat-utils.js";
export * from "./crypto.js";
export * from "./decode-wa-message.js";
export * from "./event-buffer.js";
export * from "./freezee-socket.js";
export * from "./generics.js";
export * from "./history.js";
export * from "./link-preview.js";
export * from "./logger.js";
export * from "./lt-hash.js";
export * from "./make-mutex.js";
export * from "./message-retry-manager.js";
export * from "./messages-media.js";
export * from "./messages.js";
export * from "./noise-handler.js";
export * from "./pre-key-manager.js";
export * from "./process-message.js";
export * from "./signal.js";
export * from "./socket-patcher.js";
export * from "./use-mongo-file-auth-state.js";
export * from "./use-multi-file-auth-state.js";
export * from "./validate-connection.js";

import { bindWaitForEvent } from "./generics.js";
export const bindWaitForConnectionUpdate = (ev) => bindWaitForEvent(ev, "connection.update");
